theme: minima
title: Alexandria Thylane Rohn

header_pages:
  - README.md
  - philosophy-notes.md

minima:
  social_links:
    - { platform: linkedin,  user_url: "https://www.linkedin.com/in/alexandriathylane/" }
